apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 1
  maxReplicas: 4 # пиковая нагрузка выдерживает 4 пода
  metrics: # т.к. потребление памяти у нас на одном уровне, выбираем скалирование по cpu
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60 # при достижении 60% потребления cpu будет добален еще один под#
